version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: FournisseurIdentite
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=fournisseur_identite
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Johary37
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: fournisseuridentite_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Johary37
      POSTGRES_DB: fournisseur_identite
    volumes:
      - db_data_fournisseur_identite:/var/lib/postgresql/data
      - ./conception/sql:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

volumes:
  db_data_fournisseur_identite:
