CREATE SEQUENCE etat_id_etat_seq START 1;
CREATE SEQUENCE type_reference_id_type_seq START 1;
CREATE SEQUENCE utilisateur_id_utilisateur_seq START 1;
CREATE SEQUENCE reference_id_reference_seq START 1;
CREATE SEQUENCE pin_id_pin_seq START 1;
CREATE SEQUENCE token_id_token_seq START 1;
CREATE SEQUENCE tentative_id_tentative_seq START 1;
CREATE SEQUENCE validation_inscription_id_validation_seq START 1;
CREATE SEQUENCE historique_etat_id_seq START 1;